databases:
  - name: padel-db
    plan: free

services:
  - type: web
    name: padel-api
    runtime: docker
    plan: free
    dockerfilePath: ./server/src/Padel.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__Provider
        value: PostgreSQL
      - key: DATABASE_URL
        fromDatabase:
          name: padel-db
          property: connectionString
      - key: Jwt__Issuer
        value: Padel.Api
      - key: Jwt__Audience
        value: Padel.Client
      - key: Jwt__Key
        generateValue: true
      - key: Cors__AllowedOrigins__0
        fromService:
          type: web
          name: padel-client
          envVarKey: RENDER_EXTERNAL_URL
      - key: Seed__AdminEmail
        sync: false
      - key: Seed__AdminPassword
        sync: false
      - key: MercadoPago__AccessToken
        sync: false

  - type: web
    name: padel-client
    runtime: static
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/padel-client/browser
    envVars:
      - key: API_SERVICE_URL
        fromService:
          type: web
          name: padel-api
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
